---
abstract: 'When someone replies to a resolved ticket, create a new one'
author:
  - 'Jesse Vincent <jesse@bestpractical.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  IPC::Open2: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: gplv2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RT-Extension-SplitNotOpen
no_index:
  directory:
    - inc
    - t
requires:
  MIME::Entity: 5.420
  UNIVERSAL::require: 0
version: 0.05
